print("we shall over come")
print("we shall overcome someday")
print("oho deep in my heart")
print("amra korbo joy")
print("amra korbo joy nischhhoi")
print("we shall over come we shall overcome someday oho deep in my heart amra korbo joy amra korbo joy nischhhoi")