n1=int(input("enter the 1st number:"))
n2=int(input("enter the 2nd number:"))
sign=input("enter the operation [+,-,*,/]:")
if sign == "+":print(n1 + n2)
elif sign == "-":print(n1-n2)
elif sign == "*":print(n1*n2)
elif sign == "/":print(n1/n2)